/**
 * Application error codes.
 *
 * These are the only error identifiers that may cross the API boundary.
 * Provider internals, stack traces, filesystem paths and commands must never
 * be exposed to clients.
 */
export const ErrorCode = {
  // Provider / Media
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
  PROVIDER_TIMEOUT: "PROVIDER_TIMEOUT",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  INVALID_SOURCE: "INVALID_SOURCE",
  VIDEO_NOT_FOUND: "VIDEO_NOT_FOUND",
  PLAYLIST_NOT_FOUND: "PLAYLIST_NOT_FOUND",
  STREAM_ERROR: "STREAM_ERROR",
  QUALITY_UNAVAILABLE: "QUALITY_UNAVAILABLE",
  UNSUPPORTED_OPERATION: "UNSUPPORTED_OPERATION",

  // Auth
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_TAKEN: "EMAIL_TAKEN",

  // Downloads
  DOWNLOAD_TOO_LARGE: "DOWNLOAD_TOO_LARGE",
  DOWNLOAD_TOO_LONG: "DOWNLOAD_TOO_LONG",
  DOWNLOAD_NOT_FOUND: "DOWNLOAD_NOT_FOUND",
  DOWNLOAD_FAILED: "DOWNLOAD_FAILED",
  CONVERSION_FAILED: "CONVERSION_FAILED",
  JOB_TIMEOUT: "JOB_TIMEOUT",

  // General
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
