PORT:8080
HTTP_WORKERS:2
PROXY_PART:http://localhost:7082
API_URL:http://localhost:7081
FRONTEND_URL:http://localhost:3000
BG_HELPER_URL:http://piped-bg-helper:3000
DISABLE_REGISTRATION:true
COMPROMISED_PASSWORD_CHECK:false
DISABLE_RYD:true
DISABLE_LBRY:true
DISABLE_TIMERS:false
FEED_RETENTION:30
CONSENT_COOKIE:true
hibernate.connection.url:jdbc:postgresql://piped-db:5432/piped
hibernate.connection.driver_class:org.postgresql.Driver
hibernate.dialect:org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.username:piped
hibernate.connection.password:changeme
